services:
  - type: web
    name: mutual-fund-rag-api
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: LLM_API_KEY
        sync: false
    disk:
      name: chromadb-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
